<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align="center"><font size="5">Final Project: Classification with Python</font></h1>

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
    <li><a href="https://#Section_1">Instructions</a></li>
    <li><a href="https://#Section_2">About the Data</a></li>
    <li><a href="https://#Section_3">Importing Data </a></li>
    <li><a href="https://#Section_4">Data Preprocessing</a> </li>
    <li><a href="https://#Section_5">Transforming Categorical Variables </a></li>
    <li><a href="https://#Section_6">Train and Test Data Split </a></li>
    <li><a href="https://#Section_7">Train Linear Regression, KNN, Decision Tree, Logistic Regression, and SVM models and return their appropriate accuracy scores</a></li>
</a></li>
</div>
<p>Estimated Time Needed: <strong>180 min</strong></p>
</div>

<hr>

# Instructions

In this notebook, you will  practice all the classification algorithms that we learned in this course.

After completing this notebook, you will need to upload it to the "Submit Your Work and Review Your Peers" section of the Final Project module.

Below, is where we are going to use the classification algorithms to create a model based on our training data and evaluate our testing data using evaluation metrics learned in the course.

We will use some of the algorithms taught in the course, specifically:

1.  Linear Regression
2.  KNN
3.  Decision Trees
4.  Logistic Regression
5.  SVM

We will evaluate our models using:

1.  Accuracy Score
2.  Jaccard Index
3.  F1-Score
4.  LogLoss
5.  Mean Absolute Error
6.  Mean Squared Error
7.  R2-Score

Finally, you will use your models to generate the report displaying the accuracy scores.

# About The Dataset

The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)

This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RISK_MM       | Amount of rain tomorrow                               | Millimeters     | float  |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)

## **Import the required libraries**

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn import preprocessing
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

$ \ $

-----

## ***Importing the Dataset.***

We import the required data.

In [2]:
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv')

df.head()

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes

$ \ $

----

## ***Transforming Categorical Variables.***

$(1)$ First, we need to convert categorical variables to binary variables. We will use pandas `get_dummies()` method for this.

In [3]:
df[['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm']].head()

  RainToday WindGustDir WindDir9am WindDir3pm
0       Yes           W          S        SSW
1       Yes           W          W          E
2       Yes           W        ESE        ESE
3       Yes           W        NNE          E
4       Yes           W        NNE          W

In [4]:
juli=pd.get_dummies(data=df[['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm']], columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
juli.columns

Index(['RainToday_No', 'RainToday_Yes', 'WindGustDir_E', 'WindGustDir_ENE',
       'WindGustDir_ESE', 'WindGustDir_N', 'WindGustDir_NE', 'WindGustDir_NNE',
       'WindGustDir_NNW', 'WindGustDir_NW', 'WindGustDir_S', 'WindGustDir_SE',
       'WindGustDir_SSE', 'WindGustDir_SSW', 'WindGustDir_SW', 'WindGustDir_W',
       'WindGustDir_WNW', 'WindGustDir_WSW', 'WindDir9am_E', 'WindDir9am_ENE',
       'WindDir9am_ESE', 'WindDir9am_N', 'WindDir9am_NE', 'WindDir9am_NNE',
       'WindDir9am_NNW', 'WindDir9am_NW', 'WindDir9am_S', 'WindDir9am_SE',
       'WindDir9am_SSE', 'WindDir9am_SSW', 'WindDir9am_SW', 'WindDir9am_W',
       'WindDir9am_WNW', 'WindDir9am_WSW', 'WindDir3pm_E', 'WindDir3pm_ENE',
       'WindDir3pm_ESE', 'WindDir3pm_N', 'WindDir3pm_NE', 'WindDir3pm_NNE',
       'WindDir3pm_NNW', 'WindDir3pm_NW', 'WindDir3pm_S', 'WindDir3pm_SE',
       'WindDir3pm_SSE', 'WindDir3pm_SSW', 'WindDir3pm_SW', 'WindDir3pm_W',
       'WindDir3pm_WNW', 'WindDir3pm_WSW'],
      dtype='object')

In [5]:
juli.head()

,RainToday_No,RainToday_Yes,WindGustDir_E,WindGustDir_ENE,WindGustDir_ESE,WindGustDir_N,WindGustDir_NE,WindGustDir_NNE,WindGustDir_NNW,WindGustDir_NW,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [6]:
pd.Series(list('abca'))

0    a
1    b
2    c
3    a
dtype: object

In [7]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
df_sydney_processed.columns

Index(['Date', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainTomorrow', 'RainToday_No', 'RainToday_Yes',
       'WindGustDir_E', 'WindGustDir_ENE', 'WindGustDir_ESE', 'WindGustDir_N',
       'WindGustDir_NE', 'WindGustDir_NNE', 'WindGustDir_NNW',
       'WindGustDir_NW', 'WindGustDir_S', 'WindGustDir_SE', 'WindGustDir_SSE',
       'WindGustDir_SSW', 'WindGustDir_SW', 'WindGustDir_W', 'WindGustDir_WNW',
       'WindGustDir_WSW', 'WindDir9am_E', 'WindDir9am_ENE', 'WindDir9am_ESE',
       'WindDir9am_N', 'WindDir9am_NE', 'WindDir9am_NNE', 'WindDir9am_NNW',
       'WindDir9am_NW', 'WindDir9am_S', 'WindDir9am_SE', 'WindDir9am_SSE',
       'WindDir9am_SSW', 'WindDir9am_SW', 'WindDir9am_W', 'WindDir9am_WNW',
       'WindDir9am_WSW', 'WindDir3pm_E', 'WindDir3pm_ENE', 'WindDir3pm_ESE',
       'WindDir3pm_N', 'WindDir3pm_NE', 'WindDir3pm_NNE', 'WindDir3pm_NNW',
       'WindDir3pm_NW', 'WindDir3pm_S', 'WindDir3pm_SE', 'WindDir3pm_SSE',
       'WindDir3pm_SSW', 'WindDir3pm_SW', 'WindDir3pm_W', 'WindDir3pm_WNW',
       'WindDir3pm_WSW'],
      dtype='object')

$ \ $

$(2)$ Next, we replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column. We do not use the `get_dummies` method because we would end up with two columns for 'RainTomorrow' and we do not want, since 'RainTomorrow' is our target.

In [8]:
df_sydney_processed['RainTomorrow'].head()

0    Yes
1    Yes
2    Yes
3    Yes
4    Yes
Name: RainTomorrow, dtype: object

In [9]:
print(df_sydney_processed.dtypes)

Date               object
MinTemp           float64
MaxTemp           float64
Rainfall          float64
Evaporation       float64
                   ...
WindDir3pm_SSW      uint8
WindDir3pm_SW       uint8
WindDir3pm_W        uint8
WindDir3pm_WNW      uint8
WindDir3pm_WSW      uint8
Length: 68, dtype: object

In [10]:
df_sydney_processed["RainTomorrow"].replace(['No', 'Yes'], [0,1], inplace=True)
df_sydney_processed["RainTomorrow"]

0       1
1       1
2       1
3       1
4       1
       ..
3266    0
3267    0
3268    0
3269    0
3270    0
Name: RainTomorrow, Length: 3271, dtype: int64

$ \ $

---

## ***Training Data and Test Data.***

$(1)$ Now, we set our 'features' or x values and our Y or target variable.

In [11]:
df_sydney_processed.head()

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,41,17,20,92,...,0,0,0,0,0,1,0,0,0,0
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,41,9,13,83,...,0,0,0,0,0,0,0,0,0,0
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,41,17,2,88,...,0,0,0,0,0,0,0,0,0,0
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,41,22,20,83,...,0,0,0,0,0,0,0,0,0,0
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,41,11,6,88,...,0,0,0,0,0,0,0,1,0,0

In [12]:
df_sydney_processed["Date"].head()

0    2/1/2008
1    2/2/2008
2    2/3/2008
3    2/4/2008
4    2/5/2008
Name: Date, dtype: object

In [13]:
df_sydney_processed.drop('Date', axis=1, inplace=True)

In [14]:
df_sydney_processed = df_sydney_processed.astype(float)

In [15]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

$ \ $

------


## ***Linear Regression.***

In this part we have the related exercises to linear regression.

$ \ $

$\color{aquamarine}{\text{Question (1):}}$ Use the `train_test_split` function to split the $features$ and $Y$ dataframes with:

* test_size = 0.2 

* random_state = 10

In [16]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=10)

$ \ $

$\color{aquamarine}{\text{Question (2):}}$ Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).

In [17]:
#(1) cration of a linear regression model
LinearReg = linear_model.LinearRegression()

#(2) we train our model with the previous data
LinearReg.fit(x_train, y_train)

LinearRegression()

$ \ $

$\color{aquamarine}{\text{Question (3):}}$  Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.

In [18]:
predictions = LinearReg.predict(x_test)

$ \ $

$\color{aquamarine}{\text{Question (4):}}$  Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [19]:
LinearRegression_MAE = np.mean(np.absolute(predictions - y_test))

LinearRegression_MSE = np.mean((predictions - y_test) ** 2)

LinearRegression_R2 = r2_score(predictions, y_test)

$ \ $

$\color{aquamarine}{\text{Question (5):}}$  Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.

In [20]:
Report = pd.DataFrame(data={"MAE": [LinearRegression_MAE],"MSE": [LinearRegression_MSE],"R2":[LinearRegression_R2]})
Report

        MAE      MSE        R2
0  0.256319  0.11572 -0.384931

$ \ $

----

## ***KNN (K-Nearest Neighbor).***

In this part we have the related exercises to K-Nearest Neighbor.

$ \ $

$\color{aquamarine}{\text{Question (6):}}$  Create and train a KNN model called KNN using the training data (x_train, y_train) with the n_neighbors parameter set to 4.

In [21]:
KNN = KNeighborsClassifier(n_neighbors = 4).fit(x_train, y_train)

$ \ $

$\color{aquamarine}{\text{Question (7):}}$  Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.

In [22]:
predictions = KNN.predict(x_test)

$ \ $

$\color{aquamarine}{\text{Question (8):}}$  Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [23]:
KNN_Accuracy_Score = metrics.accuracy_score(y_test, predictions)

KNN_JaccardIndex = metrics.jaccard_score(y_test, predictions)

KNN_F1_Score = metrics.f1_score(y_test, predictions)

$ \ $

----

## ***Decision Tree.***

In this part we have the related exercises to decision Tree.


$ \ $

$\color{aquamarine}{\text{Question (9):}}$  Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).

In [24]:
Tree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
Tree.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

$ \ $

$\color{aquamarine}{\text{Question (10):}}$  Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.

In [25]:
predictions = Tree.predict(x_test)

$ \ $

$\color{aquamarine}{\text{Question (11):}}$  Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [26]:
Tree_Accuracy_Score = metrics.accuracy_score(y_test, predictions)

Tree_JaccardIndex = metrics.jaccard_score(y_test, predictions)

Tree_F1_Score = metrics.f1_score(y_test, predictions)

$ \ $

----

## ***Logistic Regression.***

In this part we have the related exercises to logistic Regression.


$ \ $

$\color{aquamarine}{\text{Question (12):}}$  Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.

In [27]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=1)

$ \ $

$\color{aquamarine}{\text{Question (13):}}$  Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.

In [28]:
LR = LogisticRegression(solver='liblinear').fit(x_train, y_train)

$ \ $

$\color{aquamarine}{\text{Question (14):}}$  Now, use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.

In [29]:
predictions = LR.predict(x_test)

$ \ $

$\color{aquamarine}{\text{Question (15):}}$  Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [30]:
LR_Accuracy_Score = metrics.accuracy_score(y_test, predictions)

LR_JaccardIndex = metrics.jaccard_score(y_test, predictions)

LR_F1_Score = metrics.f1_score(y_test, predictions)

LR_Log_Loss = log_loss(y_test, predictions)

$ \ $

----

## ***SVM (support Vector Machines).***

In this part we have the related exercises to SVM (support Vector Machines). 


$ \ $

$\color{aquamarine}{\text{Question (16):}}$  Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).

In [31]:
SVM =  svm.SVC(kernel = 'rbf')

SVM.fit(x_train, y_train)

SVC()

$ \ $

$\color{aquamarine}{\text{Question (17):}}$  Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.

In [32]:
predictions = SVM.predict(x_test)

$ \ $

$\color{aquamarine}{\text{Question (18):}}$  Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [33]:
SVM_Accuracy_Score = metrics.accuracy_score(y_test, predictions)

SVM_JaccardIndex = metrics.jaccard_score(y_test, predictions)

SVM_F1_Score = metrics.f1_score(y_test, predictions)

$ \ $

-----

## ***Final report.***

In this part we show the final report.


$ \ $

$\color{aquamarine}{\text{Question (19):}}$  Show the Accuracy, Jaccard Index, F1-Score and LogLoss in a tabular format using data frame for all of the above models.

$ \ $

***Note:*** LogLoss is only for Logistic Regression Model.

In [37]:
accuracy = [KNN_Accuracy_Score, Tree_Accuracy_Score, LR_Accuracy_Score, SVM_Accuracy_Score]
jackcard = [KNN_JaccardIndex, Tree_JaccardIndex, LR_JaccardIndex, SVM_JaccardIndex]
f_1 = [KNN_F1_Score, Tree_F1_Score, LR_F1_Score, SVM_F1_Score]
log = [np.nan, np.nan, LR_Log_Loss, np.nan]


dicc = {"Accuracy": accuracy, "Jaccard Index": jackcard, "F1-Score": f_1, "LogLoss": log}
index = ["KNN","Tree","LR","SVM"]
Report = pd.DataFrame(dicc, index=index)
Report.transpose()

                    KNN      Tree        LR       SVM
Accuracy       0.818321  0.818321  0.836641  0.722137
Jaccard Index  0.425121  0.480349  0.509174  0.000000
F1-Score       0.596610  0.648968  0.674772  0.000000
LogLoss             NaN       NaN  5.642256       NaN